version: "3.8"

services:
  orchestration-based-saga:
    container_name: orchestration-based-saga
    build: ./orchestration-based-demo
    networks:
      - local
    ports:
      - "8080:8080"

networks:
  local:
    driver: bridge
